async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,l="object"==typeof process&&process.versions?.node&&"renderer"!=process.type;if(l){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var ca="./this.program",da=(a,b)=>{throw b;},ea=import.meta.url,fa="",ia,p;
if(l){var fs=require("fs");ea.startsWith("file:")&&(fa=require("path").dirname(require("url").fileURLToPath(ea))+"/");p=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(p=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)});ia=async a=>{if(ja(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ka=console.log.bind(console),q=console.error.bind(console),u,la=!1,ma,ja=a=>a.startsWith("file://"),na,oa,pa,v,w,qa,x,y,z,ra=!1;function sa(){var a=pa.buffer;v=new Int8Array(a);qa=new Int16Array(a);w=new Uint8Array(a);new Uint16Array(a);x=new Int32Array(a);y=new Uint32Array(a);new Float32Array(a);new Float64Array(a);z=new BigInt64Array(a);new BigUint64Array(a)}var E=0,ta=null;function ua(){E++;f.monitorRunDependencies?.(E)}
function va(){E--;f.monitorRunDependencies?.(E);if(0==E&&ta){var a=ta;ta=null;a()}}function wa(a){f.onAbort?.(a);a="Aborted("+a+")";q(a);la=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa?.(a);throw a;}var xa;async function ya(a){if(!u)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==xa&&u)a=new Uint8Array(u);else if(p)a=p(a);else throw"both async and sync fetching of the wasm failed";return a}
async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),wa(d)}}async function Aa(a){var b=xa;if(!u&&!ja(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return za(b,a)}
class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ca=a=>{for(;0<a.length;)a.shift()(f)},Da=[],Ea=[],Fa=()=>{var a=f.preRun.shift();Ea.push(a)},Ga=!0,Ha="undefined"!=typeof TextDecoder?new TextDecoder:void 0,F=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ia=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ia(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},H=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ka=(a,b)=>G(a+"/"+b),La=()=>{if(l){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Ma=a=>{(Ma=La())(a)},Na=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:I.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ia(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Oa=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var n=h.length-1;0<=n&&""===h[n];n--);return k>n?[]:h.slice(k,n-k+1)}a=Na(a).slice(1);b=Na(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Pa=[],Qa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=
d?(b+=4,++c):b+=3}return b},J=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},Ra=a=>{var b=Array(Qa(a)+1);a=J(a,b,0,b.length);b.length=a;return b},Sa=
[];function Ta(a,b){Sa[a]={input:[],output:[],ta:b};Ua(a,Va)}
var Va={open(a){var b=Sa[a.node.rdev];if(!b)throw new I.da(43);a.tty=b;a.seekable=!1},close(a){a.tty.ta.fsync(a.tty)},fsync(a){a.tty.ta.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ta.Ta)throw new I.da(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ta.Ta(a.tty)}catch(k){throw new I.da(29);}if(void 0===h&&0===e)throw new I.da(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ta.La)throw new I.da(60);try{for(var e=0;e<d;e++)a.tty.ta.La(a.tty,
b[c+e])}catch(g){throw new I.da(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Wa={Ta(){a:{if(!Pa.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Pa=Ra(a)}a=Pa.shift()}return a},La(a,b){null===b||10===
b?(ka(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ka(F(a.output)),a.output=[])},hb(){return{wb:25856,yb:5,vb:191,xb:35387,ub:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ib(){return 0},jb(){return[24,80]}},Xa={La(a,b){null===b||10===b?(q(F(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(q(F(a.output)),a.output=[])}},K={qa:null,ia(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===
(c&61440)||I.isFIFO(c))throw new I.da(63);K.qa||(K.qa={dir:{node:{ma:K.ea.ma,oa:K.ea.oa,lookup:K.ea.lookup,sa:K.ea.sa,rename:K.ea.rename,unlink:K.ea.unlink,rmdir:K.ea.rmdir,readdir:K.ea.readdir,symlink:K.ea.symlink},stream:{ka:K.fa.ka}},file:{node:{ma:K.ea.ma,oa:K.ea.oa},stream:{ka:K.fa.ka,read:K.fa.read,write:K.fa.write,ya:K.fa.ya,Aa:K.fa.Aa}},link:{node:{ma:K.ea.ma,oa:K.ea.oa,readlink:K.ea.readlink},stream:{}},Na:{node:{ma:K.ea.ma,oa:K.ea.oa},stream:I.cb}});c=I.createNode(a,b,c,d);M(c.mode)?(c.ea=
K.qa.dir.node,c.fa=K.qa.dir.stream,c.ga={}):I.isFile(c.mode)?(c.ea=K.qa.file.node,c.fa=K.qa.file.stream,c.ja=0,c.ga=null):40960===(c.mode&61440)?(c.ea=K.qa.link.node,c.fa=K.qa.link.stream):8192===(c.mode&61440)&&(c.ea=K.qa.Na.node,c.fa=K.qa.Na.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ga[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Jb(a){return a.ga?a.ga.subarray?a.ga.subarray(0,a.ja):new Uint8Array(a.ga):new Uint8Array(0)},ea:{ma(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;
b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M(a.mode)?b.size=4096:I.isFile(a.mode)?b.size=a.ja:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},oa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ja!=b&&(0==b?(a.ga=null,a.ja=0):(c=a.ga,a.ga=new Uint8Array(b),c&&a.ga.set(c.subarray(0,Math.min(b,
a.ja))),a.ja=b)))},lookup(){K.Da||(K.Da=new I.da(44),K.Da.stack="<generic error, no stack>");throw K.Da;},sa(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){try{var d=N(b,c)}catch(g){}if(d){if(M(a.mode))for(var e in d.ga)throw new I.da(55);Ya(d)}delete a.parent.ga[a.name];b.ga[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.ga[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=N(a,b),d;for(d in c.ga)throw new I.da(55);delete a.ga[b];a.ctime=a.mtime=Date.now()},
readdir(a){return[".","..",...Object.keys(a.ga)]},symlink(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I.da(28);return a.link}},fa:{read(a,b,c,d,e){var g=a.node.ga;if(e>=a.node.ja)return 0;a=Math.min(a.node.ja-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===v.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.ga||a.ga.subarray)){if(g)return a.ga=
b.subarray(c,c+d),a.ja=d;if(0===a.ja&&0===e)return a.ga=b.slice(c,c+d),a.ja=d;if(e+d<=a.ja)return a.ga.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.ga?a.ga.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.ga,a.ga=new Uint8Array(g),0<a.ja&&a.ga.set(h.subarray(0,a.ja),0));if(a.ga.subarray&&b.subarray)a.ga.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ga[e+g]=b[c+g];a.ja=Math.max(a.ja,e+d);return d},ka(a,b,c){1===c?b+=a.position:2===c&&I.isFile(a.node.mode)&&(b+=a.node.ja);
if(0>b)throw new I.da(28);return b},ya(a,b,c,d,e){if(!I.isFile(a.node.mode))throw new I.da(43);a=a.node.ga;if(e&2||!a||a.buffer!==v.buffer){d=!0;wa();e=void 0;if(!e)throw new I.da(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);v.set(a,e)}}else d=!1,e=a.byteOffset;return{Ob:e,qb:d}},Aa(a,b,c,d){K.fa.write(a,b,0,d,c,!1);return 0}}},Za=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},$a=async a=>{a=await ia(a);return new Uint8Array(a)},ab=[],cb=async(a,
b)=>{"undefined"!=typeof Browser&&bb();for(var c of ab)if(c.canHandle(b))return c.handle(a,b);return a},db=async(a,b,c,d,e,g,h,k)=>{var n=b?Na(G(a+"/"+b)):a;ua();try{var r=c;"string"==typeof c&&(r=await $a(c));r=await cb(r,n);k?.();if(!g){c=b;a&&(a="string"==typeof a?a:O(a),c=b?G(a+"/"+b):a);var m=Za(d,e),t=I.create(c,m);if(r){if("string"==typeof r){var C=Array(r.length);b=0;for(var L=r.length;b<L;++b)C[b]=r.charCodeAt(b);r=C}I.chmod(t,m|146);var A=I.open(t,577);I.write(A,r,0,r.length,0,h);I.close(A);
I.chmod(t,m)}}}finally{va()}};function bb(){var a,b,c;I.Ga=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?I.ua("/dev","stdin",a):I.symlink("/dev/tty","/dev/stdin");b?I.ua("/dev","stdout",null,b):I.symlink("/dev/tty","/dev/stdout");c?I.ua("/dev","stderr",null,c):I.symlink("/dev/tty1","/dev/stderr");I.open("/dev/stdin",0);I.open("/dev/stdout",1);I.open("/dev/stderr",1)}function Ua(a,b){I.Pa[a]={fa:b}}function M(a){return 16384===(a&61440)}
function N(a,b){var c=M(a.mode)?(c=P(a,"x"))?c:a.ea.lookup?0:2:54;if(c)throw new I.da(c);for(c=I.pa[eb(a.id,b)];c;c=c.xa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return I.lookup(a,b)}function Ya(a){var b=eb(a.parent.id,a.name);if(I.pa[b]===a)I.pa[b]=a.xa;else for(b=I.pa[b];b;){if(b.xa===a){b.xa=a.xa;break}b=b.xa}}
function Q(a,b={}){if(!a)throw new I.da(44);b.Ba??(b.Ba=!0);"/"===a.charAt(0)||(a=I.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=I.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Ja(e),I.Ia(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=G(e+"/"+a[g]);try{d=N(d,a[g])}catch(k){if(44===k?.ha&&h&&b.nb)return{path:e};throw k;}!d.na||h&&!b.Ba||(d=d.na.root);if(40960===(d.mode&61440)&&(!h||
b.la)){if(!d.ea.readlink)throw new I.da(52);d=d.ea.readlink(d);"/"===d.charAt(0)||(d=Ja(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new I.da(32);}function O(a){for(var b;;){if(I.Ia(a))return a=a.ia.Xa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%I.pa.length}function fb(a){var b=eb(a.parent.id,a.name);a.xa=I.pa[b];I.pa[b]=a}
function gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function P(a,b){if(I.Wa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function hb(a,b){if(!M(a.mode))return 54;try{return N(a,b),20}catch(c){}return P(a,"wx")}
function ib(a,b,c){try{var d=N(a,b)}catch(e){return e.ha}if(a=P(a,"wx"))return a;if(c){if(!M(d.mode))return 54;if(I.Ia(d)||O(d)===I.cwd())return 10}else if(M(d.mode))return 31;return 0}function jb(a,b){if(!a)throw new I.da(b);return a}function R(a){a=I.Sa(a);if(!a)throw new I.da(8);return a}function kb(a,b=-1){a=Object.assign(new I.bb,a);if(-1==b)a:{for(b=0;b<=I.Ma;b++)if(!I.streams[b])break a;throw new I.da(33);}a.fd=b;return I.streams[b]=a}function lb(a,b=-1){a=kb(a,b);a.fa?.Db?.(a);return a}
function mb(a,b,c){var d=a?.fa.oa;a=d?a:b;d??=b.ea.oa;jb(d,63);d(a,c)}function nb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.za)}return b}function ob(a){var b={tb:4096,Gb:4096,blocks:1E6,sb:5E5,rb:5E5,files:I.Ka,Eb:I.Ka-1,Hb:42,flags:2,Mb:255};a.ea.Za&&Object.assign(b,a.ea.Za(a.ia.ob.root));return b}function pb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return I.sa(a,b|8192,c)}function qb(a,b,c,d){mb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Qa:d})}
function rb(a,b,c){if(M(b.mode))throw new I.da(31);if(!I.isFile(b.mode))throw new I.da(28);var d=P(b,"w");if(d)throw new I.da(d);mb(a,b,{size:c,timestamp:Date.now()})}function sb(a,b,c,d){a="string"==typeof a?a:O(a);b=G(a+"/"+b);return I.create(b,Za(c,d))}
function tb(a){if(!(a.kb||a.lb||a.link||a.ga)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.ga=p(a.url),a.ja=a.ga.length}catch(b){throw new I.da(29);}}}
var I={root:null,za:[],Pa:{},streams:[],Ka:1,pa:null,Oa:"/",Ga:!1,Wa:!0,fb:null,Ca:0,Ya:{},da:class{name="ErrnoError";constructor(a){this.ha=a}},bb:class{ra={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ra.flags}set flags(a){this.ra.flags=a}get position(){return this.ra.position}set position(a){this.ra.position=a}},ab:class{ea={};fa={};na=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ia=a.ia;this.id=I.Ka++;this.name=b;this.mode=c;this.rdev=d;
this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get lb(){return M(this.mode)}get kb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new I.ab(a,b,c,d);fb(a);return a},Ia(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Ma:4096,Sa:a=>I.streams[a],
cb:{open(a){a.fa=I.gb(a.node.rdev).fa;a.fa.open?.(a)},ka(){throw new I.da(70);}},Ja:a=>a>>8,Kb:a=>a&255,wa:(a,b)=>a<<8|b,gb:a=>I.Pa[a],$a(a,b){function c(h){I.Ca--;return b(h)}function d(h){if(h){if(!d.eb)return d.eb=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);I.Ca++;1<I.Ca&&q(`warning: ${I.Ca} FS.syncfs operations in flight at once, probably just doing extra work`);var e=nb(I.root.ia),g=0;e.forEach(h=>{if(!h.type.$a)return d(null);h.type.$a(h,a,d)})},ia(a,b,c){var d="/"===
c;if(d&&I.root)throw new I.da(10);if(!d&&c){var e=Q(c,{Ba:!1});c=e.path;e=e.node;if(e.na)throw new I.da(10);if(!M(e.mode))throw new I.da(54);}b={type:a,ob:b,Xa:c,za:[]};a=a.ia(b);a.ia=b;b.root=a;d?I.root=a:e&&(e.na=b,e.ia&&e.ia.za.push(b));return a},Sb(a){a=Q(a,{Ba:!1});if(!a.node.na)throw new I.da(28);a=a.node;var b=a.na,c=nb(b);Object.keys(I.pa).forEach(d=>{for(d=I.pa[d];d;){var e=d.xa;c.includes(d.ia)&&Ya(d);d=e}});a.na=null;a.ia.za.splice(a.ia.za.indexOf(b),1)},lookup(a,b){return a.ea.lookup(a,
b)},sa(a,b,c){var d=Q(a,{parent:!0}).node;a=H(a);if(!a)throw new I.da(28);if("."===a||".."===a)throw new I.da(20);var e=hb(d,a);if(e)throw new I.da(e);if(!d.ea.sa)throw new I.da(63);return d.ea.sa(d,a,b,c)},Za(a){return ob(Q(a,{la:!0}).node)},Qb(a){return ob(a.node)},create(a,b=438){return I.sa(a,b&4095|32768,0)},mkdir(a,b=511){return I.sa(a,b&1023|16384,0)},Lb(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{I.mkdir(d,b)}catch(g){if(20!=g.ha)throw g;}}},symlink(a,
b){if(!Na(a))throw new I.da(44);var c=Q(b,{parent:!0}).node;if(!c)throw new I.da(44);b=H(b);var d=hb(c,b);if(d)throw new I.da(d);if(!c.ea.symlink)throw new I.da(63);return c.ea.symlink(c,b,a)},rename(a,b){var c=Ja(a),d=Ja(b),e=H(a),g=H(b);var h=Q(a,{parent:!0});var k=h.node;h=Q(b,{parent:!0});h=h.node;if(!k||!h)throw new I.da(44);if(k.ia!==h.ia)throw new I.da(75);var n=N(k,e);a=Oa(a,d);if("."!==a.charAt(0))throw new I.da(28);a=Oa(b,c);if("."!==a.charAt(0))throw new I.da(55);try{var r=N(h,g)}catch(m){}if(n!==
r){b=M(n.mode);if(e=ib(k,e,b))throw new I.da(e);if(e=r?ib(h,g,b):hb(h,g))throw new I.da(e);if(!k.ea.rename)throw new I.da(63);if(n.na||r&&r.na)throw new I.da(10);if(h!==k&&(e=P(k,"w")))throw new I.da(e);Ya(n);try{k.ea.rename(n,h,g),n.parent=h}catch(m){throw m;}finally{fb(n)}}},rmdir(a){var b=Q(a,{parent:!0}).node;a=H(a);var c=N(b,a),d=ib(b,a,!0);if(d)throw new I.da(d);if(!b.ea.rmdir)throw new I.da(63);if(c.na)throw new I.da(10);b.ea.rmdir(b,a);Ya(c)},readdir(a){a=Q(a,{la:!0}).node;return jb(a.ea.readdir,
54)(a)},unlink(a){var b=Q(a,{parent:!0}).node;if(!b)throw new I.da(44);a=H(a);var c=N(b,a),d=ib(b,a,!1);if(d)throw new I.da(d);if(!b.ea.unlink)throw new I.da(63);if(c.na)throw new I.da(10);b.ea.unlink(b,a);Ya(c)},readlink(a){a=Q(a).node;if(!a)throw new I.da(44);if(!a.ea.readlink)throw new I.da(28);return a.ea.readlink(a)},stat(a,b){a=Q(a,{la:!b}).node;return jb(a.ea.ma,63)(a)},fstat(a){var b=R(a);a=b.node;var c=b.fa.ma;b=c?b:a;c??=a.ea.ma;jb(c,63);return c(b)},lstat(a){return I.stat(a,!0)},chmod(a,
b,c){a="string"==typeof a?Q(a,{la:!c}).node:a;qb(null,a,b,c)},lchmod(a,b){I.chmod(a,b,!0)},fchmod(a,b){a=R(a);qb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?Q(a,{la:!d}).node:a;mb(null,a,{timestamp:Date.now(),Qa:d})},lchown(a,b,c){I.chown(a,b,c,!0)},fchown(a){a=R(a);mb(a,a.node,{timestamp:Date.now(),Qa:!1})},truncate(a,b){if(0>b)throw new I.da(28);a="string"==typeof a?Q(a,{la:!0}).node:a;rb(null,a,b)},Ib(a,b){a=R(a);if(0>b||0===(a.flags&2097155))throw new I.da(28);rb(a,a.node,b)},Tb(a,b,c){a=
Q(a,{la:!0}).node;jb(a.ea.oa,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new I.da(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Q(a,{la:!(b&131072),nb:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new I.da(20);}else{if(e)throw new I.da(31);d=I.sa(a,c|511,0);g=!0}if(!d)throw new I.da(44);
8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!M(d.mode))throw new I.da(54);if(!g&&(e=d?40960===(d.mode&61440)?32:M(d.mode)&&("r"!==gb(b)||b&576)?31:P(d,gb(b)):44))throw new I.da(e);b&512&&!g&&I.truncate(d,0);b&=-131713;e=kb({node:d,path:O(d),flags:b,seekable:!0,position:0,fa:d.fa,pb:[],error:!1});e.fa.open&&e.fa.open(e);g&&I.chmod(d,c&511);!f.logReadFiles||b&1||a in I.Ya||(I.Ya[a]=1);return e},close(a){if(null===a.fd)throw new I.da(8);a.va&&(a.va=null);try{a.fa.close&&a.fa.close(a)}catch(b){throw b;
}finally{I.streams[a.fd]=null}a.fd=null},ka(a,b,c){if(null===a.fd)throw new I.da(8);if(!a.seekable||!a.fa.ka)throw new I.da(70);if(0!=c&&1!=c&&2!=c)throw new I.da(28);a.position=a.fa.ka(a,b,c);a.pb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new I.da(28);if(null===a.fd)throw new I.da(8);if(1===(a.flags&2097155))throw new I.da(8);if(M(a.node.mode))throw new I.da(31);if(!a.fa.read)throw new I.da(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I.da(70);b=
a.fa.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new I.da(28);if(null===a.fd)throw new I.da(8);if(0===(a.flags&2097155))throw new I.da(8);if(M(a.node.mode))throw new I.da(31);if(!a.fa.write)throw new I.da(28);a.seekable&&a.flags&1024&&I.ka(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new I.da(70);b=a.fa.write(a,b,c,d,e,g);h||(a.position+=b);return b},ya(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new I.da(2);
if(1===(a.flags&2097155))throw new I.da(2);if(!a.fa.ya)throw new I.da(43);if(!b)throw new I.da(28);return a.fa.ya(a,b,c,d,e)},Aa(a,b,c,d,e){return a.fa.Aa?a.fa.Aa(a,b,c,d,e):0},Ha(a,b,c){if(!a.fa.Ha)throw new I.da(59);return a.fa.Ha(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c=I.open(a,b.flags);a=I.stat(a).size;var d=new Uint8Array(a);I.read(c,d,0,a,0);"utf8"===b.encoding&&
(d=F(d));I.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=I.open(a,c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(Ra(b)));if(ArrayBuffer.isView(b))I.write(a,b,0,b.byteLength,void 0,c.zb);else throw Error("Unsupported data type");I.close(a)},cwd:()=>I.Oa,chdir(a){a=Q(a,{la:!0});if(null===a.node)throw new I.da(44);if(!M(a.node.mode))throw new I.da(54);var b=P(a.node,"x");if(b)throw new I.da(b);I.Oa=a.path},Pb(){I.Ga=!1;for(var a of I.streams)a&&I.close(a)},Fb(a,b){try{var c=Q(a,
{la:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=Q(a,{parent:!0}),H(a),c=Q(a,{la:!b}),d=!0,e=c.node}catch(g){}return d?e:null},Bb(a,b){a="string"==typeof a?a:O(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{I.mkdir(d)}catch(e){if(20!=e.ha)throw e;}a=d}}return d},ua(a,b,c,d){a=Ka("string"==typeof a?a:O(a),b);b=Za(!!c,!!d);var e;(e=I.ua).Ja??(e.Ja=64);e=I.wa(I.ua.Ja++,0);Ua(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,n){for(var r=0,m=
0;m<n;m++){try{var t=c()}catch(C){throw new I.da(29);}if(void 0===t&&0===r)throw new I.da(6);if(null===t||void 0===t)break;r++;h[k+m]=t}r&&(g.node.atime=Date.now());return r},write(g,h,k,n){for(var r=0;r<n;r++)try{d(h[k+r])}catch(m){throw new I.da(29);}n&&(g.node.mtime=g.node.ctime=Date.now());return r}});return pb(a,b,e)},Ab(a,b,c,d,e){class g{Fa=!1;ra=[];Ea=void 0;Ua=0;Ra=0;get(m){if(!(m>this.length-1||0>m)){var t=m%this.chunkSize;return this.Ea(m/this.chunkSize|0)[t]}}mb(m){this.Ea=m}Va(){var m=
new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var t=Number(m.getResponseHeader("Content-length")),C,L=(C=m.getResponseHeader("Accept-Ranges"))&&"bytes"===C;m=(C=m.getResponseHeader("Content-Encoding"))&&"gzip"===C;var A=1048576;L||(A=t);var B=this;B.mb(U=>{var ha=U*A,V=(U+1)*A-1;V=Math.min(V,t-1);if("undefined"==typeof B.ra[U]){var Ob=B.ra;if(ha>V)throw Error("invalid range ("+ha+", "+V+") or no bytes requested!");
if(V>t-1)throw Error("only "+t+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);t!==A&&D.setRequestHeader("Range","bytes="+ha+"-"+V);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);ha=void 0!==D.response?new Uint8Array(D.response||[]):Ra(D.responseText||"");Ob[U]=ha}if("undefined"==typeof B.ra[U])throw Error("doXHR failed!");
return B.ra[U]});if(m||!t)A=t=1,A=t=this.Ea(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ua=t;this.Ra=A;this.Fa=!0}get length(){this.Fa||this.Va();return this.Ua}get chunkSize(){this.Fa||this.Va();return this.Ra}}if("undefined"!=typeof XMLHttpRequest){if(!ba)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var n=sb(a,b,d,e);h?n.ga=
h:k&&(n.ga=null,n.url=k);Object.defineProperties(n,{ja:{get:function(){return this.ga.length}}});var r={};Object.keys(n.fa).forEach(m=>{var t=n.fa[m];r[m]=(...C)=>{tb(n);return t(...C)}});r.read=(m,t,C,L,A)=>{tb(n);m=m.node.ga;if(A>=m.length)t=0;else{L=Math.min(m.length-A,L);if(m.slice)for(var B=0;B<L;B++)t[C+B]=m[A+B];else for(B=0;B<L;B++)t[C+B]=m.get(A+B);t=L}return t};r.ya=()=>{tb(n);wa();throw new I.da(48);};n.fa=r;return n}};
function ub(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?I.cwd():R(a).path;if(0==b.length){if(!c)throw new I.da(44);return a}return a+"/"+b}
function vb(a,b){y[a>>2]=b.dev;y[a+4>>2]=b.mode;y[a+8>>2]=b.nlink;y[a+12>>2]=b.uid;y[a+16>>2]=b.gid;y[a+20>>2]=b.rdev;z[a+24>>3]=BigInt(b.size);x[a+32>>2]=4096;x[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();z[a+40>>3]=BigInt(Math.floor(c/1E3));y[a+48>>2]=c%1E3*1E6;z[a+56>>3]=BigInt(Math.floor(d/1E3));y[a+64>>2]=d%1E3*1E6;z[a+72>>3]=BigInt(Math.floor(e/1E3));y[a+80>>2]=e%1E3*1E6;z[a+88>>3]=BigInt(b.ino);return 0}
var wb=void 0,S=()=>{var a=x[+wb>>2];wb+=4;return a},xb=0,yb=a=>0===a%4&&(0!==a%100||0===a%400),zb=[0,31,60,91,121,152,182,213,244,274,305,335],Ab=[0,31,59,90,120,151,181,212,243,273,304,334],Bb={},Cb=a=>{if(a instanceof Ba||"unwind"==a)return ma;da(1,a)},Db=a=>{ma=a;Ga||0<xb||(f.onExit?.(a),la=!0);da(a,new Ba(a))},Eb=a=>{ma=a;Db(a)},Fb=a=>{if(!la)try{if(a(),!(Ga||0<xb))try{ma=a=ma,Db(a)}catch(b){Cb(b)}}catch(b){Cb(b)}},Gb={},Ib=()=>{if(!Hb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",
HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gb)void 0===Gb[b]?delete a[b]:a[b]=Gb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hb=c}return Hb},Hb,Jb=(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=y[b>>2],k=y[b+4>>2];b+=8;h=I.read(a,v,h,k,d);if(0>h)return-1;e+=h;if(h<k)break;"undefined"!=typeof d&&(d+=h)}return e},Kb=(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=y[b>>2],k=y[b+4>>2];b+=8;h=I.write(a,v,h,k,d);
if(0>h)return-1;e+=h;if(h<k)break;"undefined"!=typeof d&&(d+=h)}return e},T;I.Cb=(a,b,c,d,e,g,h,k,n,r)=>{db(a,b,c,d,e,k,n,r).then(g).catch(h)};I.Nb=db;I.pa=Array(4096);I.ia(K,{},"/");I.mkdir("/tmp");I.mkdir("/home");I.mkdir("/home/web_user");
(function(){I.mkdir("/dev");Ua(I.wa(1,3),{read:()=>0,write:(d,e,g,h)=>h,ka:()=>0});pb("/dev/null",I.wa(1,3));Ta(I.wa(5,0),Wa);Ta(I.wa(6,0),Xa);pb("/dev/tty",I.wa(5,0));pb("/dev/tty1",I.wa(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ma(a),b=a.byteLength);return a[--b]};I.ua("/dev","random",c);I.ua("/dev","urandom",c);I.mkdir("/dev/shm");I.mkdir("/dev/shm/tmp")})();
(function(){I.mkdir("/proc");var a=I.mkdir("/proc/self");I.mkdir("/proc/self/fd");I.ia({ia(){var b=I.createNode(a,"fd",16895,73);b.fa={ka:K.fa.ka};b.ea={lookup(c,d){c=+d;var e=R(c);c={parent:null,ia:{Xa:"fake"},ea:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(I.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();I.fb={MEMFS:K};f.noExitRuntime&&(Ga=f.noExitRuntime);f.preloadPlugins&&(ab=f.preloadPlugins);f.print&&(ka=f.print);
f.printErr&&(q=f.printErr);f.wasmBinary&&(u=f.wasmBinary);f.thisProgram&&(ca=f.thisProgram);f.callMain=Lb;f.FS=I;
var Mb,Nb,W,X,Pb,Y,bc={i:(a,b,c,d)=>wa(`Assertion failed: ${a?F(w,a):""}, at: `+[b?b?F(w,b):"":"unknown filename",c,d?d?F(w,d):"":"unknown function"]),p:function(a){try{var b=R(a);return lb(b).fd}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return-c.ha}},U:function(a,b){try{var c=R(a);if(c.fd===b)return-28;if(0>b||b>=I.Ma)return-8;var d=I.Sa(b);d&&I.close(d);return lb(c,b).fd}catch(e){if("undefined"==typeof I||"ErrnoError"!==e.name)throw e;return-e.ha}},j:function(a,b,c){wb=c;
try{var d=R(a);switch(b){case 0:var e=S();if(0>e)break;for(;I.streams[e];)e++;return lb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=S(),d.flags|=e,0;case 12:return e=S(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return-g.ha}},T:function(a,b){try{return vb(b,I.fstat(a))}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return-c.ha}},F:function(a,b,c){try{var d=R(a);d.va||(d.va=I.readdir(d.path));
a=0;var e=I.ka(d,0,1),g=Math.floor(e/280),h=Math.min(d.va.length,g+Math.floor(c/280));for(c=g;c<h;c++){var k=d.va[c];if("."===k){var n=d.node.id;var r=4}else if(".."===k)n=Q(d.path,{parent:!0}).node.id,r=4;else{try{var m=N(d.node,k)}catch(t){if(28===t?.ha)continue;throw t;}n=m.id;r=8192===(m.mode&61440)?2:M(m.mode)?4:40960===(m.mode&61440)?10:8}z[b+a>>3]=BigInt(n);z[b+a+8>>3]=BigInt(280*(c+1));qa[b+a+16>>1]=280;v[b+a+18]=r;J(k,w,b+a+19,256);a+=280}I.ka(d,280*c,0);return a}catch(t){if("undefined"==
typeof I||"ErrnoError"!==t.name)throw t;return-t.ha}},C:function(a,b,c){wb=c;try{var d=R(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.ta.hb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=S();x[e>>2]=25856;x[e+4>>2]=5;x[e+8>>2]=191;x[e+12>>2]=35387;for(var g=0;32>g;g++)v[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ta.ib)for(e=S(),
a=[],g=0;32>g;g++)a.push(v[e+g+17]);return 0;case 21519:if(!d.tty)return-59;e=S();return x[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=S(),I.Ha(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ta.jb&&(g=[24,80],e=S(),qa[e>>1]=g[0],qa[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof I||"ErrnoError"!==h.name)throw h;return-h.ha}},R:function(a,b){try{return a=a?F(w,a):"",vb(b,I.lstat(a))}catch(c){if("undefined"==
typeof I||"ErrnoError"!==c.name)throw c;return-c.ha}},Q:function(a,b,c,d){try{b=b?F(w,b):"";var e=d&256;b=ub(a,b,d&4096);return vb(c,e?I.lstat(b):I.stat(b))}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return-g.ha}},o:function(a,b,c,d){wb=d;try{b=b?F(w,b):"";b=ub(a,b);var e=d?S():0;return I.open(b,c,e).fd}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return-g.ha}},D:function(a,b,c,d){try{return b=b?F(w,b):"",d=d?F(w,d):"",b=ub(a,b),d=ub(c,d),I.rename(b,d),0}catch(e){if("undefined"==
typeof I||"ErrnoError"!==e.name)throw e;return-e.ha}},E:function(a){try{return a=a?F(w,a):"",I.rmdir(a),0}catch(b){if("undefined"==typeof I||"ErrnoError"!==b.name)throw b;return-b.ha}},S:function(a,b){try{return a=a?F(w,a):"",vb(b,I.stat(a))}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return-c.ha}},n:function(a,b,c){try{b=b?F(w,b):"";b=ub(a,b);if(c)if(512===c)I.rmdir(b);else return-28;else I.unlink(b);return 0}catch(d){if("undefined"==typeof I||"ErrnoError"!==d.name)throw d;return-d.ha}},
q:()=>wa(""),z:()=>{Ga=!1;xb=0},x:()=>{throw Infinity;},I:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);x[b>>2]=a.getUTCSeconds();x[b+4>>2]=a.getUTCMinutes();x[b+8>>2]=a.getUTCHours();x[b+12>>2]=a.getUTCDate();x[b+16>>2]=a.getUTCMonth();x[b+20>>2]=a.getUTCFullYear()-1900;x[b+24>>2]=a.getUTCDay();x[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},J:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*
a);x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();x[b+8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();x[b+28>>2]=(yb(a.getFullYear())?zb:Ab)[a.getMonth()]+a.getDate()-1|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();x[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},K:function(a){var b=new Date(x[a+20>>2]+1900,x[a+
16>>2],x[a+12>>2],x[a+8>>2],x[a+4>>2],x[a>>2],0),c=x[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(g,e);0>c?x[a+32>>2]=Number(e!=g&&h==d):0<c!=(h==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?h:e)-d)));x[a+24>>2]=b.getDay();x[a+28>>2]=(yb(b.getFullYear())?zb:Ab)[b.getMonth()]+b.getDate()-1|0;x[a>>2]=b.getSeconds();x[a+4>>2]=b.getMinutes();x[a+8>>2]=b.getHours();x[a+12>>2]=b.getDate();
x[a+16>>2]=b.getMonth();x[a+20>>2]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},A:(a,b)=>{Bb[a]&&(clearTimeout(Bb[a].id),delete Bb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Bb[a];Fb(()=>Nb(a,performance.now()))},b);Bb[a]={id:c,Rb:b};return 0},L:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();y[a>>2]=60*Math.max(g,e);x[b>>2]=Number(g!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/
60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(J(a,w,c,17),J(b,w,d,17)):(J(a,w,d,17),J(b,w,c,17))},M:function(a,b,c){if(!(0<=a&&3>=a))return 28;z[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},k:()=>Date.now(),B:a=>{var b=w.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);
sa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},O:(a,b)=>{var c=0,d=0,e;for(e of Ib()){var g=b+c;y[a+d>>2]=g;c+=J(e,w,g,Infinity)+1;d+=4}return 0},P:(a,b)=>{var c=Ib();y[a>>2]=c.length;a=0;for(var d of c)a+=Qa(d)+1;y[b>>2]=a;return 0},b:Eb,h:function(a){try{var b=R(a);I.close(b);return 0}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return c.ha}},H:function(a,b,c,d,e){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(d))return 61;var g=R(a),h=
Jb(g,b,c,d);y[e>>2]=h;return 0}catch(k){if("undefined"==typeof I||"ErrnoError"!==k.name)throw k;return k.ha}},G:function(a,b,c,d,e){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(d))return 61;var g=R(a),h=Kb(g,b,c,d);y[e>>2]=h;return 0}catch(k){if("undefined"==typeof I||"ErrnoError"!==k.name)throw k;return k.ha}},l:function(a,b,c,d){try{var e=R(a),g=Jb(e,b,c);y[d>>2]=g;return 0}catch(h){if("undefined"==typeof I||"ErrnoError"!==h.name)throw h;return h.ha}},N:function(a,b,c,d){b=
-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=R(a);I.ka(e,b,c);z[d>>3]=BigInt(e.position);e.va&&0===b&&0===c&&(e.va=null);return 0}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return g.ha}},r:function(a,b,c,d){try{var e=R(a),g=Kb(e,b,c);y[d>>2]=g;return 0}catch(h){if("undefined"==typeof I||"ErrnoError"!==h.name)throw h;return h.ha}},d:Qb,e:Rb,f:Sb,v:Tb,s:Ub,w:Vb,a:Wb,c:Xb,g:Yb,m:Zb,u:$b,t:ac,y:Db},Z=await (async function(){function a(c){Z=
c.exports;pa=Z.V;sa();T=Z.Y;c=Z;f._main=Mb=c.X;Nb=c.Z;W=c._;X=c.$;Pb=c.aa;Y=c.ba;va();return Z}ua();var b={a:bc};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});xa??=f.locateFile?f.locateFile?f.locateFile("gs.wasm",fa):fa+"gs.wasm":(new URL("gs.wasm",import.meta.url)).href;return a((await Aa(b)).instance)}());function Wb(a,b){var c=Y();try{T.get(a)(b)}catch(d){X(c);if(d!==d+0)throw d;W(1,0)}}
function Xb(a,b,c){var d=Y();try{T.get(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;W(1,0)}}function Qb(a,b){var c=Y();try{return T.get(a)(b)}catch(d){X(c);if(d!==d+0)throw d;W(1,0)}}function Sb(a,b,c,d){var e=Y();try{return T.get(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;W(1,0)}}function Rb(a,b,c){var d=Y();try{return T.get(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;W(1,0)}}function Yb(a,b,c,d){var e=Y();try{T.get(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;W(1,0)}}
function Zb(a,b,c,d,e){var g=Y();try{T.get(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;W(1,0)}}function Vb(a,b,c,d){var e=Y();try{return T.get(a)(b,c,d)}catch(g){X(e);if(g!==g+0)throw g;W(1,0)}}function Tb(a,b,c,d,e){var g=Y();try{return T.get(a)(b,c,d,e)}catch(h){X(g);if(h!==h+0)throw h;W(1,0)}}function $b(a,b,c,d,e,g){var h=Y();try{T.get(a)(b,c,d,e,g)}catch(k){X(h);if(k!==k+0)throw k;W(1,0)}}
function ac(a,b,c,d,e,g,h){var k=Y();try{T.get(a)(b,c,d,e,g,h)}catch(n){X(k);if(n!==n+0)throw n;W(1,0)}}function Ub(a,b,c,d,e,g,h,k,n){var r=Y();try{return T.get(a)(b,c,d,e,g,h,k,n)}catch(m){X(r);if(m!==m+0)throw m;W(1,0)}}function Lb(a=[]){var b=Mb;a.unshift(ca);var c=a.length,d=Pb(4*(c+1)),e=d;a.forEach(h=>{var k=y,n=e>>2,r=Qa(h)+1,m=Pb(r);J(h,w,m,r);k[n]=m;e+=4});y[e>>2]=0;try{var g=b(c,d);Eb(g,!0);return g}catch(h){return Cb(h)}}
function cc(){function a(){f.calledRun=!0;if(!la){ra=!0;f.noFSInit||I.Ga||bb();Z.W();I.Wa=!1;na?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Da.push(b)}Ca(Da)}}if(0<E)ta=cc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Fa();Ca(Ea);0<E?ta=cc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();cc();ra?moduleRtn=f:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default Module;
